server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: inabox
  config:
    import:
      - "optional:file:.env[.properties]"
  security:
    user:
      name: admin
      password: ${custom.admin.password}
      roles: USER,ADMIN
  mongodb:
    uri: ${custom.mongo.uri}
#  web:
#    error:
#      include-message: always
logging:
  level:
    '[org.mongodb.driver.protocol.command]': INFO
    '[org.springframework.data.mongodb.core.MongoTemplate]': INFO
