spring:
  application:
    name: inabox
  config:
    import:
      - "optional:file:.env[.properties]"
  security:
    user:
      name: admin
      password: ${custom.admin.password}
      roles: USER,ADMIN # Optional: specify roles as a comma-separated list
  # Moved entirely out of 'data' to satisfy Spring Boot 4 & Eclipse
  mongodb:
    uri: ${custom.mongo.uri}
logging:
  level:
    '[org.mongodb.driver.protocol.command]': DEBUG
    '[org.springframework.data.mongodb.core.MongoTemplate]': DEBUG
